import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope & typeof globalThis;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// --- Push Notification Logic ---

self.addEventListener('push', (event: PushEvent) => {
    console.log('[Service Worker] Push received:', event);

    let notificationData = {
        title: 'ITJ Travel',
        body: 'Anda memiliki notifikasi baru',
        icon: '/icons/icon-192x192.svg',
        badge: '/icons/badge-72x72.svg',
        data: { url: '/' }
    };

    if (event.data) {
        try {
            notificationData = { ...notificationData, ...event.data.json() };
        } catch (e) {
            notificationData.body = event.data.text();
        }
    }

    const options: NotificationOptions = {
        body: notificationData.body,
        icon: notificationData.icon,
        badge: notificationData.badge,
        vibrate: [100, 50, 100, 50, 100],
        data: notificationData.data,
        tag: notificationData.tag || 'default',
        requireInteraction: notificationData.requireInteraction || false,
        actions: (notificationData as any).type === 'panic' ? [
            { action: 'view', title: 'Lihat Lokasi' },
            { action: 'dismiss', title: 'Tutup' }
        ] : []
    };

    event.waitUntil(
        self.registration.showNotification(notificationData.title, options)
    );
});

self.addEventListener('notificationclick', (event: NotificationEvent) => {
    console.log('[Service Worker] Notification click:', event);

    event.notification.close();

    let url = '/';
    if (event.notification.data && event.notification.data.url) {
        url = event.notification.data.url;
    }

    if (event.action === 'view' || !event.action) {
        event.waitUntil(
            self.clients.matchAll({ type: 'window', includeUncontrolled: true })
                .then((clientList) => {
                    for (const client of clientList) {
                        if (client.url.includes(self.location.origin) && 'focus' in client) {
                            (client as WindowClient).navigate(url);
                            return (client as WindowClient).focus();
                        }
                    }
                    if (self.clients.openWindow) {
                        return self.clients.openWindow(url);
                    }
                })
        );
    }
});

// App update logic
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
